<?php

/**
 * Manager for Buy to order history object
 * 
 * @author    Senthil <senthil.kumar@sage.com>
 * @copyright 2018 Intacct Corporation All, Rights Reserved
 */

/**
 * Class BuyToOrderHistoryManager
 */
class BuyToOrderHistoryManager extends SCMMacroResolveManager
{
    /**
     * @param array $params
     */
    public function __construct($params = array())
    {
        parent::__construct($params);
    }
    
}