<?
//===========================================================================
//	FILE: SerialMaskManager.cls
//	AUTHOR: Manoj Mahur
//	DESCRIPTION:
//
//	(C) 2000, Intacct Corporation, All Rights Reserved
//
//	This document contains trade secret data that belongs to Intacct
//	Corporation and is protected by the copyright laws.  Information
//	herein may not be used, copied or disclosed in whole or in part
//	without prior written consent from Intacct Corporation.
//===========================================================================

/**
 *    Class to manage a Serial Mask for serial number tracking 
 */
class DocumententryTrackkitManager extends EntityManager
{
}
