<?php
/**
 * =============================================================================
 *
 * FILE:        BinEditor.cls
 * AUTHOR:      Sri Vidya
 * DESCRIPTION: Editor class for handelling Bin object
 *
 * (C)2000,2009 Intacct Corporation, All Rights Reserved
 *
 * Intacct Corporation Proprietary Information.
 * This document contains trade secret data that belongs to Intacct
 * corporation and is protected by the copyright laws. Information herein
 * may not be used, copied or disclosed in whole or part without prior
 * written consent from Intacct Corporation.
 * =============================================================================
 */

/**
 * Editor class for InventoryWorkQueueEditor object
 */
class InventoryWorkQueueEditor extends FormEditor
{

    /**
     * @param array $obj
     *
     * @return bool
     */
    protected function mediateDataAndMetadata(&$obj)
    {
        // $state = $this->getState();
        // TODO
        return true;
    }

}
