<?php
/**
 * This is the Inventory (INV) Recurring templates Subtotals Manager
 *  
 * @author    mjagadish <mjagadish@intacct.com>
 * @copyright 2000 Intacct Corporation All, Rights Reserved
 */

import('RecurSubTotalsManager');

/**
 *    INV Recurring SubTotals Manager
 *    required to handle the dimensions in subtotals
 */

/**
 * Class InvRecurSubTotalsManager
 */
class InvRecurSubTotalsManager extends RecurSubTotalsManager
{
}
