<?php

/**
 * Manager class for itemgrpmember object
 * 
 * @author    Senthil <skumar@intacct.com>
 * @copyright 2000 Intacct Corporation All, Rights Reserved
 */

/**
 * Owned object class for itemgrpmember
 */

/**
 * Class ItemGrpMemberManager
 */
class ItemGrpMemberManager extends OwnedObjectManager
{

    /**
     * @param array $params
     */
    public function __construct($params = array())
    {
        parent::__construct($params);
    }

}


