<?php
/**
 * File ReplenishmentRunManager.cls contains the class ReplenishmentRunManager
 *
 * @author    Roger Collins
 * @copyright 2000-2018 Intacct Corporation
 *
 * This document contains trade secret data that belongs to Intacct
 * Corporation and is protected by the copyright laws.  Information
 * herein may not be used, copied or disclosed in whole or in part
 * without prior written consent from Intacct Corporation.
 */

/**
 * Manages CRUD for Replenishment Run
 *
 * Class ReplenishmentRunManager
 */
class ReplenishmentRunManager extends EntityManager
{

}