<?php

/**
 * Editor class for Warehouse Group
 * 
 * @author    Anish <anishk@intacct.com>
 * @copyright 2000 Intacct Corporation All, Rights Reserved
 */

/**
 * Class WarehouseGroupEditor
 */
class WarehouseGroupEditor extends DimensionGroupEditor
{

    /**
     * @param array $params
     */
    public function __construct($params = array())
    {
        parent::__construct($params);
    }

}
